print("Hello World")
print(5)
print("Bye")
print("Hello world" , 7)
print(17*13)

print("Quiz Answer")
print("Stopping by Woods on a Snowy Evening - By Robert Frost")
print("Whose woods these are I think I know.")
print("His house is in the village though;")
print("He will not see me stopping here")
print("To watch his woods fill up with snow.")
print("My little horse must think it queer")
print("To stop without a farmhouse near")
print("Between the woods and frozen lake")
print("The darkest evening of the year.")
print("He gives his harness bells a shake")
print("To ask if there is some mistake.")
print("The only other sound’s the sweep")
print("Of easy wind and downy flake.")
print("The woods are lovely, dark and deep,")
print("But I have promises to keep,")
print("And miles to go before I sleep,")
print("And miles to go before I sleep.")
